CREATE TABLE public.controle_gastos (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor float8 NULL,
    categoria text NULL,
    descrição text NULL,
    data timestamptz NULL DEFAULT now(),
    outros text NULL
